# Generated by Django 3.0.2 on 2020-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.TextField()),
                ('saude', models.TextField()),
                ('industria', models.TextField()),
                ('financas', models.TextField()),
            ],
        ),
    ]
