# Generated by Django 3.0.2 on 2020-05-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200429_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcoes',
        ),
    ]
